### ISSUE TITLE
Create smaller clickable images (254x254 is too big!)

### ISSUE THREAD

**Issue by drgrubman** [consbio/Leaflet.Basemaps#25]
### How can I make the clickable images smaller?

`<script>
    var mymap = L.map('mapid').setView([51.505, -0.09], 13);

    var basemaps = [
        L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
            maxZoom: 19,

            label: 'Street'
        }),
        L.tileLayer('http://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}', {
            maxZoom: 19,
            label: 'Satellite'
        }),
    ]
    mymap.addControl(L.control.basemaps({
        basemaps: basemaps,
        tileX: 0,
        tileY: 0,
        tileZ: 1
    }));

    /*Marker*/
    var markerGroup = new L.FeatureGroup();

    markerGroup.addTo(mymap);

    //LIHTC Pin
    var LIHTC = new L.Icon({
        iconUrl: 'https://raw.githubusercontent.com/pointhi/leaflet-color-markers/master/img/marker-icon-yellow.png',
        shadowUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.7/images/marker-shadow.png',
        iconSize: [25, 41],
        iconAnchor: [12, 41],
        popupAnchor: [1, -34],
        shadowSize: [41, 41]
    });

    //Market Pin
    var Market = new L.Icon({
        iconUrl: 'https://raw.githubusercontent.com/pointhi/leaflet-color-markers/master/img/marker-icon-blue.png',
        shadowUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.7/images/marker-shadow.png',
        iconSize: [25, 41],
        iconAnchor: [12, 41],
        popupAnchor: [1, -34],
        shadowSize: [41, 41],
        html: 2,
    });

    //Subject Pin
    var Subject = new L.Icon({
        iconUrl: 'https://raw.githubusercontent.com/pointhi/leaflet-color-markers/master/img/marker-icon-violet.png',
        shadowUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.7/images/marker-shadow.png',
        iconSize: [25, 41],
        iconAnchor: [12, 41],
        popupAnchor: [1, -34],
        shadowSize: [41, 41],
        number: 2,
    });

    function pma_style(feature) {
        return {
            fillColor: 'blue',
            weight: 4,
            opacity: 1,
            color: 'red', //Outline color
            fillOpacity: 0.0
        };
    }

    $.ajax({
        type: "GET",
        url: "{% url 'workbench:kml' wb.id %}",
        success: function(data) {
            L.geoJSON(data, {
                style: pma_style
            }).addTo(markerGroup);
        },
        error: function(jqXHR, textStatus, errorThrown) {
            alert(jqXHR.status);
        },
        dataType: "json",
    });

    $.ajax({
        type: "GET",
        url: "{{ request.get_full_path }}",
        success: function(data) {
            var json = JSON.stringify(data);
            var obj = JSON.parse(json);
            console.log(obj)

            /*Loop Comps*/
            for (var i = 0; i < obj.length; i++) {

                if (obj[i].status == "Subject") {
                    marker = new L.marker([obj[i].latitude, obj[i].longitude], {
                            icon: Subject,
                            draggable: true
                        })
                        .bindTooltip("Subject", {
                            permanent: true,
                            direction: 'left'
                        })
                        .openTooltip()
                        .addTo(markerGroup).addTo(mymap).on('ready',
                            function() {});

                } else if (obj[i].program == "LIHTC") {
                    marker = new L.marker([obj[i].latitude, obj[i].longitude], {
                            icon: LIHTC,
                            draggable: true
                        })
                        .bindTooltip(String(obj[i].id), {
                            permanent: true,
                            direction: 'left'
                        })
                        .openTooltip()
                        .addTo(markerGroup).addTo(mymap).on('ready',
                            function() {});

                } else {
                    marker = new L.marker([obj[i].latitude, obj[i].longitude], {
                            icon: Market,
                            draggable: true
                        })
                        .bindTooltip(String(obj[i].id), {
                            permanent: true,
                            direction: 'left'
                        })
                        .openTooltip()
                        .addTo(markerGroup).addTo(mymap).on('ready',
                            function() {});
                }
            }
            mymap.fitBounds(markerGroup.getBounds());

        },
        error: function(jqXHR, textStatus, errorThrown) {
            alert(jqXHR.status);
        },
        dataType: "json",
    });

</script>`

**Comment by brendan-ward** [comment]
Hi @drgrubman 

The default size of the icons is `64px` - if your images are bigger, you probably have root CSS on your site that is overriding that size.

To set the size to something other than `64px` (once you have any overrides on your site out of the way), you can override the style for [`.basemap img`](https://github.com/consbio/Leaflet.Basemaps/blob/master/L.Control.Basemaps.css#L22-L28) in your own CSS, and use `!important` suffix to make sure that your override takes precedence.
