### ISSUE TITLE
Save layermap choice.

### ISSUE THREAD

**Issue by TZAdvantage** [consbio/Leaflet.Basemaps#26]
I am looking for a way to set a map layer differently as the first one.
The goal is to save the maplayer the user is on and use that for the next visit.
What would be the best way to accomplish that.

**Comment by brendan-ward** [comment]
There are a couple options:

- persist this to a server via API call for that user, and then fetch this during page loading
- use [`localStorage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) to persist this, and pull from local storage on page load if it is set.

**Comment by TZAdvantage** [comment]
Hi Brendan,
very quick response! :)

i tried it with localstorage but was not successfull.
I changed the code a bit where the first tilelayer is made active like so:
            if (d.options.className === (localStorage['basemap'] || 'gfb')) {
                this.basemap = d;
                this._map.addLayer(d);
                basemapClass += " active";
            } else if (i === 1) {
                basemapClass += " alt";
            }
I have 3 different ones and i added a className to the options which i need to use later for a color scheme. I used this to set the value in localStorage.
Works well except when the value is the second layer. Then the if (i === 1) is true and makes all tile icons disappear. Did not figure out why yet...

**Comment by RickGlimmer** [comment]
I temporarily solved it by changing the order of the layers in the basemaps array.
Not the best as then the order of the tiles is changed but it serves the purpose. :)

**Comment by brendan-ward** [comment]
@TZAdvantage I think one solution is to manage the order of the basemaps outside this plugin, before it is called (untested idea).

1. First, add an event handler for the map's "baselayerchange" event that we call [here](https://github.com/consbio/Leaflet.Basemaps/blob/master/L.Control.Basemaps.js#L106) after setting the active basemap.  Persist the ID of this basemap to local storage for the user.  No additional changes should be necessary in this session.
2. On page load, check for a basemap ID in local storage.  Then using that, reorder your list of basemaps to put that into the first position (roughly, filter for the basemap that matches that ID into one array, then concat the remaining basemaps onto that array).
3. Pass this new orded array into basemaps set in options on this plugin when it is instantiated.  That will ensure that the user's preferred basemap is always in the first position, is loaded by default into the map, etc.

**Comment by RickGlimmer** [comment]
Hi Brendan,
That is exactly how I 'solved' it. :)
each layer has an extra 'className' property in the options for display purposes (svg line colors are different depending on the used tilelayer). I use this className property to save it in localstorage.

    let classNames = [];
    basemaps.forEach(function (item, index) {
        classNames.push(item.options.className);
    });
    let savedBasemap = localStorage['basemap'] || classNames[0];
    if (savedBasemap != classNames[0]) {
        for (let i = basemaps.length - 1; i > 0; i--) {
            let item = basemaps[i];
            if (item.options.className === savedBasemap) {
                let copy = basemaps.splice(i, 1);
                basemaps.unshift(copy[0]);
                break;
            }
        };
    }
    map.on("baselayerchange", function (e) {
        const className = e.newLayer.options.className;
        localStorage['basemap'] = className;
        þMe.removeClass(classNames.join(' ')).addClass(className);
    });

The only 'problem' is that visually they are not always in the same order.
