### ISSUE TITLE
Changing map crs with changing tileLayer

### ISSUE THREAD

**Issue by webleaf** [consbio/Leaflet.Basemaps#9]
Is it possible?

**Comment by brendan-ward** [comment]
@webleaf we've never used Leaflet with anything other than a Web Mercator CRS.  I thought having more control over that was one of the cool things coming in Leaflet 1.0, but haven't been following it closely.

Can you please give me a bit more context here?  Some example basemaps in other CRS, and how you'd want that to behave when you switch between them?

**Comment by webleaf** [comment]
Yandex Maps uses other CRS. So if i want use their tiles, i have to change map.options.crs like this:

```
L.tileLayer(
    'http://vec{s}.maps.yandex.net/tiles?l=map&v=4.55.2&z={z}&x={x}&y={y}&scale=2&lang=en', {
        subdomains: ['01', '02', '03', '04'],
        reuseTiles: true,
        updateWhenIdle: false
    }
).addTo(map);

map.options.crs = L.CRS.EPSG3395;
```

**Comment by brendan-ward** [comment]
How about this?  Attach to the base layer changed event

```
L.tileLayer(
    'http://vec{s}.maps.yandex.net/tiles?l=map&v=4.55.2&z={z}&x={x}&y={y}&scale=2&lang=en', {
        subdomains: ['01', '02', '03', '04'],
        reuseTiles: true,
        updateWhenIdle: false,
        crs: L.CRS.EPSG3395
    }
).addTo(map);


map.on('baselayerchange', function (e) {
    map.options.crs = e.options.crs;
});
```

**Comment by webleaf** [comment]
Thank you for solution. Looks properly.
But in practice, does not want to work:
`leaflet.js:5 Uncaught TypeError: Cannot read property 'pointToLatLng' of undefined`

**Comment by brendan-ward** [comment]
@webleaf I tried working up an example on this, but from what I'm seeing, changing the `map.options.crs` does not actually handle this correctly (I don't get the same errors as you above).  I am unable to find other good examples of dynamically changing the CRS and basemaps in Leaflet. 

Do you have a working example where you can manually change from spherical mercator (most basemaps) to elliptical mercator (Yandex) and have the map update properly?

**Comment by brendan-ward** [comment]
Closing due to lack of working example changing CRS in Leaflet.
